add host-based routing docs
encode/starlette pull request #1313
Opened 2021-10-16 13:13 UTC by WhiteApfel

Yesterday I wanted to use host-based routing, saw the necessary methods in the Starlette class, but did not find any info in docs. After searching, I found #363 and decided to add at least a minimal mention of host-based routing to the documentation.

#369 opened almost three years ago and is still open 🤡

2021-10-19 14:27 UTC, aminalaee requested changes

2021-10-19 14:27 UTC, aminalaee commented on docs/routing.md
> +## Host-based routing
I think documenting host-based routing, and subdomains without documenting URL reversing and lookups is not complete:
```python
request.url_for("...", subdomain=...)
request.url_for("api:...")
...
```

2021-10-19 14:39 UTC, WhiteApfel commented on docs/routing.md
> +## Host-based routing
@aminalaee, then it will be better to place `Host-based routing` between `Submounting routes` and `Reverse URL lookups` sections? Because information about `url_for` should be in the `Reverse URL lookups`

2021-10-19 14:44 UTC, aminalaee commented on docs/routing.md
> +## Host-based routing
TBH, I've done this before but couldn't decide where the best place for that would be.
Maybe after `Reverse URL lookups`? Let's go with this and see if we can find any other places.

2021-10-19 14:52 UTC, WhiteApfel commented on docs/routing.md
> +## Host-based routing
We in `Reverse URL lookups` describe what was above. No, of course we can put all the information about host-based in one section, but I don't know how correct it will be

2021-10-19 14:57 UTC, aminalaee commented on docs/routing.md
> +## Host-based routing
Sorry I'm not sure if I understand correctly. In the current version of docs we do have examples for submounts but are there any examples of subdomains?
`request.url_for("endpoint", subdomain=...)`

2021-10-19 15:04 UTC, WhiteApfel commented on docs/routing.md
> +## Host-based routing
No. They are not present in the current version. I want to add example for host-submounts, but I'm just deciding where to place the information.

2021-10-19 15:49 UTC, aminalaee commented on docs/routing.md
> +## Host-based routing
I think having a section for subdomains after `Reverse lookup is fine`. Maybe later we can find a better place for it.

2021-10-23 09:02 UTC, aminalaee reviewed
```python
...
routes = [
     Host('api.example.org', api)
 ]
 app = Starlette(routes=routes)
 app.host('www.example.org', site)
 news_host = Host('news.example.org', news)
 app.router.routes.append(news_host)
```

I think this is much better. Do you think we may need a little explanation here?

2021-10-23 22:22 UTC, WhiteApfel commented
> There are several ways to connect host-based routes to your application

It'll do? I think that this does not make much sense, because the meaning from the upper sections is duplicated

2021-10-25 07:39 UTC, aminalaee commented
That makes sense.

2021-10-25 07:50 UTC, aminalaee approved these changes
Thank you for this.

2021-10-25 07:51 UTC, merged